package org.acme.kogito

import org.acme.kogito.model.Product;



rule "product"
	when
		productObject: Product(date.getCurrentTime() - date.getTime() < 5)
	then
		productObject.setDiscount(15);
		System.out.println("Product going to expiry soon!!!");
	end
rule "product"
	when
		productObject: Product(date.getCurrentTime() - date.getTime() < 2)
	then
		productObject.setDiscount(50);
		System.out.println("Product going to expiry very soon!!!");
	end
